# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Release

on:
  push:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: make test

      - name: Build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          bash
          make release
          echo "##[set-env name=VERSION;]$(make version)"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: automatic release
          tag_name: ${ VERSION }
          draft: true
          files: |
            /build/syncer-darwin-amd64.tar.gz
            /build/syncer-darwin-arm64.tar.gz
            /build/syncer-linux-amd64.tar.gz
            /build/syncer-linux-arm64.tar.gz
            /build/syncer-windows-amd64.tar.gz
            /build/syncer-windows-arm64.tar.gz
